#!/bin/bash
xdotool key Super_L+1
xdotool sleep 0.3
xdotool key Left control+t
xdotool type "https://resheba.top/gdz/8-klass"
xdotool key Return
xdotool key Left control+t
xdotool type "https://megaresheba.ru/"
xdotool key Return
